### ISSUE TITLE
almost there?

### ISSUE THREAD

**Issue by designosis** [niranjan94/payumoney-php#3]
This looks really great! But I can't get it to work. I have a half-dozen other composer requires (phpmailer, browscap, instamojo, etc.), and all install and work fine. I think there's something wrong with the namespaces, but I can't figure out what. I get constant **`Fatal error: Uncaught Error: Class 'PayUMoney' not found`** errors. I've tried varying the namespace, changing from psr4 to psr0, repeaded `dump-autoload`s, etc. ... no luck.

I'd love to use your code! Any suggestions on getting this to work?

On a related note ... your usage doc is incorrect. It says `$client->initializePurchase($params)->send();` where (I think) it should say `$payumoney->initializePurchase($params)->send();`.

**Comment by designosis** [comment]
This really does look like the cleanest / simplest implementation for payumoney. If you have any advice, I'd love to hear it.

**Comment by niranjan94** [comment]
@neokio Good to know that you like it :) ... I have fixed the typo in the doc. Thanks ! :smile: 

Have pushed a new version. Could you update now and give it a try ?

**Comment by designosis** [comment]
Of course. If you're telling me that you've recently tested your code on a clean install using the most recent version of composer, and everything works as-is, it's possible there's some bizarre incompatibility in my setup. But given how fresh the code is, I'd suggest there may be a problem in the codebase. Just can't really tell where :)

**Comment by designosis** [comment]
Yep v1.1 fixed it :) Thank you!

**Comment by niranjan94** [comment]
@neokio you're welcome :)
